let numbers: number[] = [1, 2, 3, 4, 5];
numbers.push(6);
numbers.pop(); 
numbers[0] = 10; 
console.log(numbers);
let student: [string, number] = ["Alice", 90];
let name1: string = student[0];
let grade: number = student[1];
console.log(name, grade); 
let point: [number, number, string] = [10, 20, "A"]; 